CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar UNIQUE,
  "password" varchar,
  "phone_number" varchar,
  "address" text,
  "role" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "workshops" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "name" varchar,
  "description" text,
  "address" text,
  "phone_number" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "services" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "workshop_id" int,
  "name" varchar,
  "description" text,
  "price" decimal,
  "duration" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "spare_parts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "workshop_id" int,
  "name" varchar,
  "description" text,
  "price" decimal,
  "stock" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "transactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "workshop_id" int,
  "transaction_type" varchar,
  "total_price" decimal,
  "payment_status" varchar,
  "payment_method" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "transaction_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transaction_id" int,
  "item_type" varchar,
  "item_id" int,
  "quantity" int,
  "price" decimal,
  "is_additional" boolean DEFAULT false,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "workshop_reports" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "workshop_id" int,
  "total_transactions" int,
  "total_revenue" decimal,
  "total_spare_parts_sold" int,
  "total_services_completed" int,
  "report_period" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "chats" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "workshop_id" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "chat_messages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chat_id" int,
  "sender_id" int,
  "message" text,
  "sent_at" timestamp,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "workshop_ratings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "workshop_id" int,
  "rating" int,
  "review" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "service_reminders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "name" varchar,
  "description" text,
  "reminder_date" date,
  "is_completed" boolean DEFAULT false,
  "created_at" timestamp,
  "updated_at" timestamp
);

ALTER TABLE "workshops" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "services" ADD FOREIGN KEY ("workshop_id") REFERENCES "workshops" ("id");

ALTER TABLE "spare_parts" ADD FOREIGN KEY ("workshop_id") REFERENCES "workshops" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("workshop_id") REFERENCES "workshops" ("id");

ALTER TABLE "transaction_items" ADD FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("id");

ALTER TABLE "workshop_reports" ADD FOREIGN KEY ("workshop_id") REFERENCES "workshops" ("id");

ALTER TABLE "chats" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "chats" ADD FOREIGN KEY ("workshop_id") REFERENCES "workshops" ("id");

ALTER TABLE "chat_messages" ADD FOREIGN KEY ("chat_id") REFERENCES "chats" ("id");

ALTER TABLE "chat_messages" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id");

ALTER TABLE "workshop_ratings" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "workshop_ratings" ADD FOREIGN KEY ("workshop_id") REFERENCES "workshops" ("id");

ALTER TABLE "service_reminders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
