name: Authentication Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: motoflex
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Delvinet7475
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, pgsql

    - name: Cache Composer Packages
      uses: actions/cache@v4
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install Dependencies
      run: composer install --no-progress --prefer-dist

    - name: Copy .env
      run: cp .env.example .env

    - name: Set Environment Variables
      run: |
        echo "APP_KEY=base64:TestKeyForCI1234567890===" >> .env
        echo "DB_CONNECTION=pgsql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=5432" >> .env
        echo "DB_DATABASE=motoflex" >> .env
        echo "DB_USERNAME=postgres" >> .env
        echo "DB_PASSWORD=Delvinet7475" >> .env

    - name: Generate Key
      run: php artisan key:generate

    - name: Run Migrations
      run: php artisan migrate --force

    - name: Run Auth Migrations
      run: php artisan migrate --path=vendor/devdojo/auth/database/migrations --force

    - name: Install PestPHP & Dusk
      run: composer require pestphp/pest laravel/dusk alebatistella/duskapiconf --dev --with-all-dependencies

    - name: Run Tests
      run: php artisan test
