name: Authentication Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Delvinet7475
          POSTGRES_DB: motoflex
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, pgsql

    - name: Cache Composer Packages
      uses: actions/cache@v4
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-git

    - name: Install Dependencies
      run: composer install --no-progress --prefer-dist

    - name: Remove current tests and symlink to DevDojo Auth
      run: |
        rm -rf tests
        ln -s vendor/devdojo/auth/tests tests

    - name: Copy .env file
      run: cp .env.example .env

    - name: Set environment variables for PostgreSQL
      run: |
        sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=pgsql/' .env
        sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
        sed -i 's/DB_PORT=.*/DB_PORT=5432/' .env
        sed -i 's/DB_DATABASE=.*/DB_DATABASE=motoflex/' .env
        sed -i 's/DB_USERNAME=.*/DB_USERNAME=postgres/' .env
        sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=Delvinet7475/' .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Remove config cache file
      run: rm -f bootstrap/cache/config.php

    - name: Clear config cache
      run: php artisan config:clear

    - name: Run the migrations
      run: php artisan migrate

    - name: Run the Auth Migrations
      run: php artisan migrate --path=vendor/devdojo/auth/database/migrations

    - name: Install PestPHP and Laravel Dusk
      run: composer require pestphp/pest laravel/dusk alebatistella/duskapiconf --dev --with-all-dependencies

    - name: Run Tests
      run: php artisan test
